In [2]:
from transformers import BertTokenizer, BertModel

tokenizer = BertTokenizer.from_pretrained("bert-base-multilingual-uncased")
model = BertModel.from_pretrained("bert-base-multilingual-uncased")

C:\Users\Miki\AppData\Roaming\Python\Python310\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Some weights of the model checkpoint at bert-base-multilingual-uncased were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expe

In [39]:
inputs = tokenizer("fiú", return_tensors="pt")
outputs = model(**inputs)

last_hidden_states = outputs.last_hidden_state

BERT esetén az outputs[0]=last_hidden_states

In [47]:
print(last_hidden_states)
print(last_hidden_states.shape)

tensor([[[-0.1822, -0.1136,  0.0338,  ..., -0.0102, -0.0928,  0.0013],
         [ 0.3587,  0.5455,  0.2915,  ...,  0.1090, -0.3925, -0.4721],
         [-0.0497,  0.3051,  0.1879,  ...,  0.4382, -0.3410, -0.6537]]],
       grad_fn=<NativeLayerNormBackward0>)
torch.Size([1, 3, 768])


In [72]:
from scipy.spatial import distance
import numpy as np

sum=0
cnt=0
avg=0

baseword="fiú"
encoded_input_base=tokenizer(baseword,return_tensors='pt')
output_base = model(**encoded_input_base)
output_base_np=output_base.last_hidden_state[0].detach().numpy()
#print(output_base_np.shape)
#print(output_base_np)


synonym="férfi"
encoded_input_synonym=tokenizer(synonym,return_tensors='pt')
output_synonym = model(**encoded_input_synonym)
output_synonym_np=output_synonym.last_hidden_state[0].detach().numpy()
#print(output_synonym_np.shape)
#print(output_synonym_np)

#print('-'*100)

#embedded_base_avg=np.average(output_base.last_hidden_state[0].detach().numpy(), axis=0)
embedded_base_avg=np.average(output_base_np, axis=0)
#print(embedded_base_avg)
#embedded_synonym_avg=np.average(output_synonym.last_hidden_state[0].detach().numpy(), axis=0)
embedded_synonym_avg=np.average(output_synonym_np, axis=0)
#print(embedded_synonym_avg)
dist=distance.cosine(embedded_base_avg,embedded_synonym_avg)
sum=sum+dist
cnt=cnt+1
# overall result on synonym-dictionary
#print(cnt, end="\r")
        
avg=sum/cnt
print(avg)

0.3563584089279175


In [67]:
# testing how it works
import numpy as np
np_arr_last_state=last_hidden_states[0].detach().numpy()
print(np_arr_last_state.shape)
print(np_arr_last_state)
print()
a=np.average(np_arr_last_state, axis=0)
print(a)
print(type(a[0]))
print(len(a))


(3, 768)
[[-0.18216443 -0.11355147  0.03382306 ... -0.01024304 -0.0928133
   0.00134867]
 [ 0.358693    0.54547423  0.29153946 ...  0.10896264 -0.39252383
  -0.47214147]
 [-0.04971064  0.3051269   0.187889   ...  0.4381922  -0.34095812
  -0.65374905]]

[ 4.22726460e-02  2.45683238e-01  1.71083823e-01 -9.82998610e-02
 -1.50804535e-01  2.61594325e-01  1.96309105e-01 -1.11682676e-01
 -6.51286840e-01  1.59975260e-01 -4.20032591e-01 -2.81877398e-01
  3.56755018e-01 -4.88238007e-01  1.72184870e-01 -1.98071480e-01
 -4.07284647e-01  3.26663792e-01 -3.24718833e-01  2.20212355e-01
  1.01651251e-03  3.88452381e-01 -2.82478541e-01 -3.71165842e-01
  5.82455218e-01  9.79720950e-02 -1.51532844e-01  2.12154031e-01
 -3.71146113e-01 -3.76954645e-01 -4.32430983e-01 -1.28883943e-01
 -6.33491948e-02  4.17957157e-01 -1.25011489e-01 -1.81900918e-01
  2.28518501e-01  4.41793680e-01  4.22350019e-01 -2.46386096e-01
 -3.93648863e-01 -2.42304221e-01  4.86900099e-02 -1.61074564e-01
  7.58043155e-02  5.38158529e-02

In [60]:
# testing how it works
import numpy as np

arr = np.array([[2,3,4,5],
                [3,6,7,1],
                [5,7,8,3]])
print(arr)
print(arr.shape)
a= np.average(arr,axis=0)
print(a)

[[2 3 4 5]
 [3 6 7 1]
 [5 7 8 3]]
(3, 4)
[3.33333333 5.33333333 6.33333333 3.        ]


In [9]:
print(outputs[0].size())
print(outputs[0][0])

torch.Size([1, 3, 768])
tensor([[-0.1604,  0.0217,  0.0308,  ..., -0.1492, -0.1486,  0.0202],
        [-0.0013,  0.4526, -0.0767,  ..., -0.1619, -0.3329, -0.0555],
        [-0.2374,  0.1104,  0.0320,  ..., -0.3034, -0.4189, -0.1706]],
       grad_fn=<SelectBackward0>)


In [10]:
print(last_hidden_states.size())
print(last_hidden_states)

torch.Size([1, 3, 768])
tensor([[[-0.1604,  0.0217,  0.0308,  ..., -0.1492, -0.1486,  0.0202],
         [-0.0013,  0.4526, -0.0767,  ..., -0.1619, -0.3329, -0.0555],
         [-0.2374,  0.1104,  0.0320,  ..., -0.3034, -0.4189, -0.1706]]],
       grad_fn=<NativeLayerNormBackward0>)


In [5]:
import numpy
print(numpy.array_equal(last_hidden_states.detach().numpy(),outputs[0].detach().numpy()))

True
